#!/bin/bash

#
# coordinator
#
coordinator_cfg_file="$IMPLY_HOME/conf/druid/coordinator/runtime.properties"
coordinator_jvm_file="$IMPLY_HOME/conf/druid/coordinator/jvm.config"

export COORDINATOR_service=${COORDINATOR_service:=druid/coordinator}
export COORDINATOR_port=${COORDINATOR_port:=8081}

export COORDINATOR_coordinator_startDelay=${COORDINATOR_coordinator_startDelay:=PT30S}
export COORDINATOR_coordinator_period=${COORDINATOR_coordinator_period:=PT30S}


echo '# Generated by druid-master-entrypoint.sh' > ${coordinator_cfg_file}
while read -r var; do
  key=$(echo $var | sed -r 's/COORDINATOR_(.*)=.*/druid_\1/g' | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${coordinator_cfg_file}
done < <(env | grep '^COORDINATOR_' | sort)

export COORDINATOR_JAVA_OPTIONS=${COORDINATOR_JAVA_OPTIONS:='-server -Xms256m -Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dderby.stream.error.file=var/druid/derby.log'}

rm -f ${coordinator_jvm_file}
for var in $COORDINATOR_JAVA_OPTIONS; do
	echo "$var" >> ${coordinator_jvm_file}
done

echo "Coordinator jvm configuration:"
echo "-------------------------"
cat ${coordinator_jvm_file}
echo ""
echo "Coordinator runtime configuration:"
echo "-----------------------------"
cat ${coordinator_cfg_file}
echo ""

#
# overlord
#
overlord_cfg_file="$IMPLY_HOME/conf/druid/overlord/runtime.properties"
overlord_jvm_file="$IMPLY_HOME/conf/druid/overlord/jvm.config"

export OVERLORD_service=${OVERLORD_service:=druid/overlord}
export OVERLORD_port=${OVERLORD_port:=8090}

export OVERLORD_indexer_queue_startDelay=${OVERLORD_indexer_queue_startDelay:=PT30S}

export OVERLORD_indexer_runner_type=${OVERLORD_indexer_runner_type:=remote}
export OVERLORD_indexer_storage_type=${OVERLORD_indexer_storage_type:=metadata}

echo '# Generated by druid-master-entrypoint.sh' > ${overlord_cfg_file}
while read -r var; do
  key=$(echo $var | sed -r 's/OVERLORD_(.*)=.*/druid_\1/g' | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${overlord_cfg_file}
done < <(env | grep '^OVERLORD_' | sort)

export OVERLORD_JAVA_OPTIONS=${OVERLORD_JAVA_OPTIONS:='-server -Xms256m -Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager'}

rm -f ${overlord_jvm_file}
for var in $OVERLORD_JAVA_OPTIONS; do
	echo "$var" >> ${overlord_jvm_file}
done

echo "Overlord jvm configuration:"
echo "-------------------------"
cat ${overlord_jvm_file}
echo ""
echo "Overlord runtime configuration:"
echo "-----------------------------"
cat ${overlord_cfg_file}
echo ""

/druid-base-entrypoint.sh "$@"