#!/bin/bash

#
# broker
#
broker_cfg_file="$IMPLY_HOME/conf/druid/broker/runtime.properties"
broker_jvm_file="$IMPLY_HOME/conf/druid/broker/jvm.config"

export BROKER_service=${BROKER_service:=druid/broker}
export BROKER_port=${BROKER_port:=8082}

# HTTP server threads
export BROKER_broker_http_numConnections=${BROKER_broker_http_numConnections:=5}
export BROKER_server_http_numThreads=${BROKER_server_http_numThreads:=40}

# Processing threads and buffers
export BROKER_processing_buffer_sizeBytes=${BROKER_processing_buffer_sizeBytes:=256000000}
export BROKER_processing_numThreads=${BROKER_processing_numThreads:=2}

# Query cache disabled -- push down caching and merging instead
export BROKER_broker_cache_useCache=${BROKER_broker_cache_useCache:=false}
export BROKER_broker_cache_populateCache=${BROKER_broker_cache_populateCache:=false}


echo '# Generated by druid-query-entrypoint.sh' > ${broker_cfg_file}
while read -r var; do
  key=$(echo $var | sed -r 's/BROKER_(.*)=.*/druid_\1/g' | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${broker_cfg_file}
done < <(env | grep '^BROKER_' | sort)

export BROKER_JAVA_OPTIONS=${BROKER_JAVA_OPTIONS:='-server -Xms1g -Xmx1g -XX:MaxDirectMemorySize=1280m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager'}

rm -f ${broker_jvm_file}
for var in $BROKER_JAVA_OPTIONS; do
	echo "$var" >> ${broker_jvm_file}
done

echo "Broker jvm configuration:"
echo "-------------------------"
cat ${broker_jvm_file}
echo ""
echo "Broker runtime configuration:"
echo "-----------------------------"
cat ${broker_cfg_file}
echo ""

/druid-base-entrypoint.sh "$@"