---
  - name: provides development environment for ubuntu
    hosts: local
    tasks:
      - name: install ubuntu packages
        apt: pkg={{ item }} update_cache=yes
        with_items:
          - vim
          - python-dev
          - python3-dev
          - python-pip
          - python3-pip
          - gcc
          - clang
      - name: install pip2 packages
        pip:  name={{ item }} executable=pip
        with_items:
          - cython
      - name: install pip3 packages
        pip: name={{ item }} executable=pip3
        with_items:
          - cython