version: '2'

services:
  namenode:
    image: itrust/hdfs:2.7.1
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    command: /run-namenode.sh
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      #- YARN_CONF_yarn_log___aggregation___enable=true
      #- YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      #- YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      #- YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      #- YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      #- YARN_CONF_yarn_log_server_url=http://historyserver.hadoop:8188/applicationhistory/logs/
      #- YARN_CONF_yarn_timeline___service_enabled=true
      #- YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      #- YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      #- YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      #- YARN_CONF_yarn_timeline___service_hostname=historyserver.hadoop
    ports:
      - "50070:50070"

  datanode1:
    image: itrust/hdfs:2.7.1
    hostname: datanode1
    container_name: datanode1
    links:
        - namenode
    domainname: hadoop
    command: /run-datanode.sh
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      #- YARN_CONF_yarn_log___aggregation___enable=true
      #- YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      #- YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      #- YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      #- YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      #- YARN_CONF_yarn_log_server_url=http://historyserver.hadoop:8188/applicationhistory/logs/
      #- YARN_CONF_yarn_timeline___service_enabled=true
      #- YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      #- YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      #- YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      #- YARN_CONF_yarn_timeline___service_hostname=historyserver.hadoop
