version: '2'

services:
    zookeeper:
        image: itrust/zookeeper
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888

    kafka:
        image: itrust/kafka
        container_name: kafka
        links:
            - zookeeper
        ports:
            - 9092:9092
