#!/bin/bash

sr_cfg_file="${CONFLUENT_HOME}/etc/schema-registry/schema-registry.properties"

: ${SCHEMA_REGISTRY_PORT:=9081}
: ${SCHEMA_REGISTRY_KAFKASTORE_TOPIC:=_schemas}
: ${SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL:=zookeeper:2181}
: ${SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR:=1}
: ${SCHEMA_REGISTRY_DEBUG:=false}

export SCHEMA_REGISTRY_PORT
export SCHEMA_REGISTRY_KAFKASTORE_TOPIC
export SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
export SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
export SCHEMA_REGISTRY_DEBUG

# Download the config file, if given a URL
if [ ! -z "$SR_CFG_URL" ]; then
  echo "[SR] Downloading SR config file from ${SR_CFG_URL}"
  curl --location --silent --insecure --output ${sr_cfg_file} ${SR_CFG_URL}
  if [ $? -ne 0 ]; then
    echo "[SR] Failed to download ${SR_CFG_URL} exiting."
    exit 1
  fi
fi

echo '# Generated by start-schema_registry.sh' > ${sr_cfg_file}
for var in $(env | grep '^SCHEMA_REGISTRY_' | sort); do
  key=$(echo $var | sed -r 's/SCHEMA_REGISTRY_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${sr_cfg_file}
done

exec ${CONFLUENT_HOME}/bin/schema-registry-start ${sr_cfg_file}
