#!/bin/bash

#
# middleManager
#
midmanager_cfg_file="$IMPLY_HOME/conf/druid/middleManager/runtime.properties"
midmanager_jvm_file="$IMPLY_HOME/conf/druid/middleManager/jvm.config"

export MIDMANAGER_service=${MIDMANAGER_service:=druid/middlemanager}
export MIDMANAGER_port=${MIDMANAGER_port:=8091}

# Number of tasks per middleManager
export MIDMANAGER_worker_capacity=${MIDMANAGER_worker_capacity:=3}

# Task launch parameters
export MIDMANAGER_indexer_runner_javaOpts=${MIDMANAGER_indexer_runner_javaOpts:='-server -Xmx2g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager'}
export MIDMANAGER_indexer_task_baseTaskDir=${MIDMANAGER_indexer_task_baseTaskDir:=var/druid/task}
export MIDMANAGER_indexer_task_restoreTasksOnRestart=${MIDMANAGER_indexer_task_restoreTasksOnRestart:=true}

# HTTP server threads
export MIDMANAGER_server_http_numThreads=${MIDMANAGER_server_http_numThreads:=40}

# Processing threads and buffers
export MIDMANAGER_processing_buffer_sizeBytes=${MIDMANAGER_processing_buffer_sizeBytes:=256000000}
export MIDMANAGER_processing_numThreads=${MIDMANAGER_processing_numThreads:=2}

# Hadoop indexing
export MIDMANAGER_indexer_task_hadoopWorkingPath=${MIDMANAGER_indexer_task_hadoopWorkingPath:=var/druid/hadoop-tmp}
export MIDMANAGER_indexer_task_defaultHadoopCoordinates=${MIDMANAGER_indexer_task_defaultHadoopCoordinates:='["org.apache.hadoop:hadoop-client:2.3.0"]'}


echo '# Generated by druid-data-entrypoint.sh' > ${midmanager_cfg_file}
while read -r var; do
  key=$(echo $var | sed -r 's/MIDMANAGER_(.*)=.*/druid_\1/g' | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${midmanager_cfg_file}
done < <(env | grep '^MIDMANAGER_' | sort)

export MIDMANAGER_JAVA_OPTIONS=${MIDMANAGER_JAVA_OPTIONS='-server -Xms64m -Xmx64m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Dhadoop.hadoop.tmp.dir=var/hadoop-tmp -Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager'}

rm -f ${midmanager_jvm_file}
for var in $MIDMANAGER_JAVA_OPTIONS; do
	echo "$var" >> ${midmanager_jvm_file}
done

echo " MidManager jvm configuration:"
echo "-------------------------"
cat ${midmanager_jvm_file}
echo ""
echo "MidManagerruntime configuration:"
echo "-----------------------------"
cat ${midmanager_cfg_file}
echo ""

#
# historical
#
historical_cfg_file="$IMPLY_HOME/conf/druid/historical/runtime.properties"
historical_jvm_file="$IMPLY_HOME/conf/druid/historical/jvm.config"

export HISTORICAL_service=${HISTORICAL_service:=druid/historical}
export HISTORICAL_port=${HISTORICAL_port:=8083}

# HTTP server threads
export HISTORICAL_server_http_numThreads=${HISTORICAL_server_http_numThreads:=40}

# Processing threads and buffers
export HISTORICAL_processing_buffer_sizeBytes=${HISTORICAL_processing_buffer_sizeBytes:=256000000}
export HISTORICAL_processing_numThreads=${HISTORICAL_processing_numThreads:=2}

# Segment storage
export HISTORICAL_segmentCache_locations=${HISTORICAL_segmentCache_locations:='[{"path":"var/druid/segment-cache","maxSize"\:300000000000}]'}
export HISTORICAL_server_maxSize=${HISTORICAL_server_maxSize:=300000000000}

# Query cache
export HISTORICAL_historical_cache_useCache=${HISTORICAL_historical_cache_useCache:=true}
export HISTORICAL_historical_cache_populateCache=${HISTORICAL_historical_cache_populateCache:=true}
export HISTORICAL_cache_type=${HISTORICAL_cache_type:=local}
export HISTORICAL_cache_sizeInBytes=${HISTORICAL_cache_sizeInBytes:=10000000}

echo '# Generated by druid-data-entrypoint.sh' > ${historical_cfg_file}
while read -r var; do
  key=$(echo $var | sed -r 's/HISTORICAL_(.*)=.*/druid_\1/g' | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${historical_cfg_file}
done < <(env | grep '^HISTORICAL_' | sort)

export HISTORICAL_JAVA_OPTIONS=${HISTORICAL_JAVA_OPTIONS='-server -Xms1g -Xmx1g -XX:MaxDirectMemorySize=1280m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager'}

rm -f ${historical_jvm_file}
for var in $HISTORICAL_JAVA_OPTIONS; do
	echo "$var" >> ${historical_jvm_file}
done

echo "Historical jvm configuration:"
echo "-------------------------"
cat ${historical_jvm_file}
echo ""
echo "Historical runtime configuration:"
echo "-----------------------------"
cat ${historical_cfg_file}
echo ""

/druid-base-entrypoint.sh "$@"